export default {
  OPCO: [
    { value: "All Companies", display: "All Companies" },
    { value: "SoCo", display: "SoCo" },
  ],
  STATES: [
    { value: "Select a state", display: "Select a state" },
    { value: "ALABAMA", display: "AL" },
    { value: "ALASKA", display: "AK" },
    { value: "AMERICAN SAMOA", display: "AS" },
    { value: "ARIZONA", display: "AZ" },
    { value: "ARKANSAS", display: "AR" },
    { value: "CALIFORNIA", display: "CA" },
    { value: "COLORADO", display: "CO" },
    { value: "CONNECTICUT", display: "CT" },
    { value: "DELAWARE", display: "DE" },
    { value: "DISTRICT OF COLUMBIA", display: "DC" },
    { value: "FEDERATED STATES OF MICRONESIA", display: "FM" },
    { value: "FLORIDA", display: "FL" },
    { value: "GEORGIA", display: "GA" },
    { value: "GUAM", display: "GU" },
    { value: "HAWAII", display: "HI" },
    { value: "IDAHO", display: "ID" },
    { value: "ILLINOIS", display: "IL" },
    { value: "INDIANA", display: "IN" },
    { value: "IOWA", display: "IA" },
    { value: "KANSAS", display: "KS" },
    { value: "KENTUCKY", display: "KY" },
    { value: "LOUISIANA", display: "LA" },
    { value: "MAINE", display: "ME" },
    { value: "MARSHALL ISLANDS", display: "MH" },
    { value: "MARYLAND", display: "MD" },
    { value: "MASSACHUSETTS", display: "MA" },
    { value: "MICHIGAN", display: "MI" },
    { value: "MINNESOTA", display: "MN" },
    { value: "MISSISSIPPI", display: "MS" },
    { value: "MISSOURI", display: "MO" },
    { value: "MONTANA", display: "MT" },
    { value: "NEBRASKA", display: "NE" },
    { value: "NEVADA", display: "NV" },
    { value: "NEW HAMPSHIRE", display: "NH" },
    { value: "NEW JERSEY", display: "NJ" },
    { value: "NEW MEXICO", display: "NM" },
    { value: "NEW YORK", display: "NY" },
    { value: "NORTH CAROLINA", display: "NC" },
    { value: "NORTH DAKOTA", display: "ND" },
    { value: "NORTHERN MARIANA ISLANDS", display: "MP" },
    { value: "OHIO", display: "OH" },
    { value: "OKLAHOMA", display: "OK" },
    { value: "OREGON", display: "OR" },
    { value: "PALAU", display: "PW" },
    { value: "PENNSYLVANIA", display: "PA" },
    { value: "PUERTO RICO", display: "PR" },
    { value: "RHODE ISLAND", display: "RI" },
    { value: "SOUTH CAROLINA", display: "SC" },
    { value: "SOUTH DAKOTA", display: "SD" },
    { value: "TENNESSEE", display: "TN" },
    { value: "TEXAS", display: "TX" },
    { value: "UTAH", display: "UT" },
    { value: "VERMONT", display: "VT" },
    { value: "VIRGIN ISLANDS", display: "VI" },
    { value: "VIRGINIA", display: "VA" },
    { value: "WASHINGTON", display: "WA" },
    { value: "WEST VIRGINIA", display: "WV" },
    { value: "WISCONSIN", display: "WI" },
    { value: "WYOMING", display: "WY" },
  ],
};
